### ISSUE TITLE
Programmatic instructions for gae

### ISSUE THREAD

**Issue by Yehonal** [nodyn/nodyn#99]
I'm trying to deploy nodyn on google app engine to run nodejs on its jvm. However gae accepts only java web servlet so i should load nodyn inside a java/jsp source and run programmatically.

Could you help me to create an "Hello world" code for this scope? then i'll write a guide for this purpose if it works.

Would be nice to support nodejs on gae before they will ( maybe) support it.

thank you in advance

**Comment by pancosances** [comment]
Hi,
instructions to run nodyn from JVM directly, will be really helpful.

**Comment by lance** [comment]
@pancosances @Yehonal - This should provide you with information to get you going.

**Comment by Yehonal** [comment]
thank you @lance !

**Comment by pancosances** [comment]
System.setProperty( "nodyn.binary", "./bin/node" );

This means, application in java depends on binary file node? How we can run javaScript in java, without access to filesystem? For example, I would like to run java program on Tomcat.
I though that everything is packaged in JAR file - but in this case how to update node.js modules?

**Comment by lance** [comment]
Have you tried it and failed? If so, please let me know what the issue is. Node.js internals like this property to be set. Nowhere in my message did I say anything about not having access to the filesystem.

—
Lance Ballhttp://lanceball.com

**Comment by pancosances** [comment]
Do not need to apologize, we are developers and everybody know it is very hard without caffeine, sometimes impossible. (=

Our situation is: we want to run javascript (DOM included) on the server side in Apache Tomcat Web Application, but we do not have access to server file system, so we can't install node.js directly on server. We can only deploy .war file with .jar files included. This is why I was scared with "/bin/node", because there is no way to install it and I thought, that the Nodyn runtime strictly depends on binary file /bin/node.

We can run simple javascript via DynJS, newRunner, withSourceCode, execute ... similar way like Nodyn is running, but we want also jsdom (npm module which implements the DOM and HTML standards). So in this case we have to somehow include/import/install module on local pc and compile everything to .jar library.

**Comment by lance** [comment]
If you use the undocumented (and potentially subject to change) nodyn function `__native_require` in your JS files, it will look for resources in your classpath. So, you should be able to include a javascript file, e.g.` __native_require('resources/jsdom')`. This doesn't work _exactly_ like node's `require`, however, and I haven't tried using it with an NPM module per se. Your best bet is to try and use something like browserfy to turn the module into a single file and include that in your jar. Also, I noticed that jsdom is using contextify which appears to be using native code. If this is the case, I'm sorry to say it won't work with nodyn yet.

**Comment by Yehonal** [comment]
What exactly "System.setProperty( "nodyn.binary", "./bin/node" );" is used for? 
i thought nodyn was something similar to ringojs ( http://ringojs.org/get_started ) et similia: a js interpreter that is written in java. Isn't it?

_if it's just a bridge_ between a nodejs installation and java applications , it can't be used with google app engine since this one is a PaaS where you don't have system access.
_else_ can we avoid to specify a nodejs binary ?

**Comment by lance** [comment]
@Yehonal I've updated the readme, as this is only necessary for the CLI (which is not required when embedding) and not a general purpose need.
